### ISSUE TITLE
Nimble 'install' doesn't seem to work

### ISSUE THREAD

**Issue by matkuki** [jerous86/nimqt#1]
Hi,

Thank you for this library 🎉🎉🎉

I have followed the instructions to install it with:
`nimble install https://github.com/jerous86/nimqt`
but it only installs the ˙nimqt.nimble˙ file into `.nimble/pgks/nimqt-0.1/` directory:
![image](https://user-images.githubusercontent.com/10289651/210149847-7cd0a6fe-e816-4d02-85e9-c59167632653.png)

When trying to use the library after that, I get:
![image](https://user-images.githubusercontent.com/10289651/210149879-117e735c-686a-48fd-b904-965002e2f56a.png)

**Comment by matkuki** [comment]
Specs:
- OS: `Windows 10 x64`
- Nim: `Nim Compiler Version 1.6.10 [Windows: amd64]`

**Comment by jerous86** [comment]
This library has not been tested yet on windows, so there might be many issues :)
This might be due to `/src/` symlinking to `/qt/6.4.1_minimal/`. I updated the nimble file to directly link to the latter. Can you try again with the latest commit?

**Comment by matkuki** [comment]
> This library has not been tested yet on windows, so there might be many issues :)

No worries, I will test it as much as I can. Hopefully you won't be too annoyed if I open a lot of issues as I find them.

> Can you try again with the latest commit?

Yes, now it starts compiling, thanks 👍
But now I get an error while compiling the minimal example:
```nim
# First, we import the nimqt.nim module that will allow us to use the Qt system
import nimqt

# nimqt.init() should be called at the start of your program.
# It will initialize verdigris, and import some common modules.
nimqt.init()

let app = newQApplication() # Create your application.

import nimqt/qlabel

let w=newQLabel(Q"Hello world!")
w.show()

discard app.exec() # Run Qt's main loop
```
... with this message:
```
C:\Users\matic\.nimble\pkgs\nimqt-0.1\nimqt\qtcore\qbytearray.nim(170, 1) Error: redefinition of 'setNum'; previous declaration here: C:\Users\matic\.nimble\pkgs\nimqt-0.1\nimqt\qtcore\qbytearray.nim(164, 6)
```

**Comment by jerous86** [comment]
> [...] Hopefully you won't be too annoyed if I open a lot of issues as I find them.
Not at all :)

> C:\Users\matic\.nimble\pkgs\nimqt-0.1\nimqt\qtcore\qbytearray.nim(170, 1) Error: redefinition of 'setNum'; previous declaration here: C:\Users\matic\.nimble\pkgs\nimqt-0.1\nimqt\qtcore\qbytearray.nim(164, 6)

I see what's going on: 
* overloaded proc setNum which differs only in 1 parameter: `clong` vs `cint`
* `type cint=int32` (https://github.com/nim-lang/Nim/blob/version-1-6/lib/system.nim#L1416)
* On Windows, `type clong=int32` (https://github.com/nim-lang/Nim/blob/version-1-6/lib/system.nim#L1396)
* On everything else, `type clong=int`
* Thus on Windows we have indeed twice an identical proc ...

I have no idea yet on how to resolve this simple and automatically. Any suggestions? :)

**Comment by matkuki** [comment]
Confirming that adding a `when not defined(windows):` for the `clong` and `culong` `setNum` overloads in `qtcore/qbytearray.nim` and `qtcore/qstring.nim` fixes this error.
Then I get a similar error as the #2 issue.

No idea for an automatic solution currently, sorry. Only a conditional `when` comes to mind.

**Comment by jerous86** [comment]
The automated fix was not too difficult, luckily, so it should be fixed now.

**Comment by matkuki** [comment]
Yes, it works 👍👍👍
