### ISSUE TITLE
loadUi does not work if the widget is not named rootWg

### ISSUE THREAD

**Issue by InventorXtreme** [jerous86/nimqt#27]
The code:

```import os

import nimqt
import nimqt/[load_ui,qboxlayout]

nimqt.init
let app = newQApplication(commandLineParams())

# We use `curFileDir`, defined in nimqt/load_ui to get the directory of *this* file.
# loadUi works best with absolute paths.
var win:ptr QWidget
win.loadUi("/home/inventorx/t.ui", createConnections=true)


win.show()
discard app.exec()
```

which is a direct copy of the example loading UI files code, but with rootWg replaced with win does not compile and gives an Error: undeclared identifier: 'rootWg'" error on compile.

This does not seem like intended behavior.

**Comment by jerous86** [comment]
Indeed not intended behavior. It should be fixed in the latest commit.
Thanks for reporting

**Comment by InventorXtreme** [comment]
I checked and verified that it works properly now. Thank you for the fix.
