### ISSUE TITLE
I don't know wether this is an error

### ISSUE THREAD

**Issue by grd** [jerous86/nimqt#31]
So let's name this a problem ;-)

I just started with my own app with nimqt. I use vscode and I use the load_ui.nim as an example. In there I have an error at the line 

`import nimqt/tools/load_ui`

and everything that relates to that also gets an error. I think that the import feature can't find the tools directory.

But I can compile the program with `make load_ui`

This is pretty annoying because I don't know what the solution is.

**Comment by jerous86** [comment]
I don't use vscode, so I'm afraid I will not be able to help you with this.

Do you have the same problem if you import something like `import nimqt/qtwidgets/qwidget`?
I recently moved load_ui to nimqt/tools, so maybe you have two versions of the nimqt repo, one of which is outdated?

**Comment by grd** [comment]
It was indeed the cache. Sorry, my mistake.
