### ISSUE TITLE
About the new menu item

### ISSUE THREAD

**Issue by grd** [jerous86/nimqt#32]
Yes, it works ;-) I saw the documentation and I also did run the program.

What I actually meant was this: https://en.wikipedia.org/wiki/Menu_(computing)#/media/File:Menu_(computing)_example.PNG

Can your new menu also be integrated in a program with a horizontal bar at the top with a couple of menu items, like this https://doc.qt.io/qt-5/qtwidgets-mainwindows-menus-example.html ? 

Or is this the same as your implementation?

**Comment by jerous86** [comment]
I updated `examples/menu.nim` to also include a menu bar, so it is possible and is similar to the qt example.

**Comment by grd** [comment]
Wow! It works wonderful. I am closing the issue now. Thanks!
