### ISSUE TITLE
toolBaar 2

### ISSUE THREAD

**Issue by Martinix75** [jerous86/nimqt#39]
Hello and a good 2024 !!!!!
Return again to the toolbar issue, because it works well now and it is clearly easy to implement it.
But I wondered if you could add to the macro (I will never understand the macro) as in the "File Menu":
'*' -> to add a separator (convenient to separate the various contexts)
And
'+' -> that (but I'm not sure) should create "under selection menu" on the tool bar (I don't know if this is possible I have never tried).

Thanks again for the exceptional work, and a great new year from Martin A.

**Comment by jerous86** [comment]
I will add something this week, hopefully.
Don't have much time these days :)

**Comment by jerous86** [comment]
I don't think it's feasible to add it; trying with `-` or `---` as a symbol results in syntax errors.
I think it's better and easier to just use `addSeparator0()`.
