### ISSUE TITLE
Problems with some Signal -> Slot

### ISSUE THREAD

**Issue by Martinix75** [jerous86/nimqt#47]
HI!
Working a bit with Nimqt I realized that there are some problems with calls such as qslide -> Valuechanged () (and I also believe others), in essence the aal function is not made when changing value, and the Compiler is not happy! I don't understand why this does not function and click () of qpuschbutton dispel well! (I don't want to be my mistake that I don't see!)
Small example ...
```nim
import os
import nimqt
import nimqt/qdialog
import nimqt/tools/menu
import nimqt/[qgridlayout, qlabel, qpushbutton, qboxlayout, qpixmap, qgridlayout, qslider]

nimqt.init()

let
  app = newQApplication(commandLineParams())
  finestra = newQDialog()

inheritQObject(BottoneX, QPushButton):
  slot_defer funct_bot():
    echo(" ------- Button Pressed -----------")

inheritQObject(SliderX, QSlider):
  slot_defer funct_slid():
    echo(" ------- Slider Change -----------")

let bot_1 = newBottoneX()
bot_1.setText(Q "Press Me")

let sl_1 = newSliderX()
sl_1.setRange(500, 5000)
sl_1.setOrientation(Qt_Orientation.Horizontal)

finestra.makeLayout:
  - use_object bot_1:
    connect(SIGNAL "clicked()", bot_1, SLOT "funct_bot()") #<--- work!!!!
  - use_object sl_1:
    connect(SIGNAL "valueChanged()", sl_1, SLOT "funct_slid()") #<-- not work???????
    
nimqt.insertAllSlotImplementations

finestra.setGeometry(00,00,400,200)
finestra.show()
discard app.exec()
```
this is the problem:
```
Hint: mm: orc; threads: on; opt: none (DEBUG BUILD, `-d:release` generates faster code)
78332 lines; 4.555s; 256.336MiB peakmem; proj: /home/andrea/Programmazione/Atlas/valvolaAXSQt/example.nim; out: /home/andrea/Programmazione/Atlas/valvolaAXSQt/example [SuccessX]
Hint: /home/andrea/Programmazione/Atlas/valvolaAXSQt/example [Exec]
qt.core.qobject.connect: QObject::connect: No such signal SliderX::valueChanged()
 ------- Button Pressed -----------
 ------- Button Pressed -----------
 ------- Button Pressed -----------
```
Valuechanged () does not even work on other widgets (for example qspinbox ()).
And also others like Slidermoved () do not work!
bye by Andrea

**Comment by jerous86** [comment]
Hi Andrea,
The problem is indicated here:
> qt.core.qobject.connect: QObject::connect: No such signal SliderX::valueChanged()

If you look at https://doc.qt.io/qt-5/qabstractslider.html#valueChanged, then you can see that valueChanged requires 1 argument.

So if you update the corresponding lines to `connect(SIGNAL "valueChanged(int)", sl_1, SLOT "funct_slid(int)")` and `  slot_defer funct_slid(x:int):` (i.e. add the `int` parameter) then it works.

Good luck!

**Comment by Martinix75** [comment]
wow is true !!
I hadn't seen that it took a "int" argoment. I really need holidays, which are there today !!
Thank you very much and to take you bye bye from Andrea
