### ISSUE TITLE
[Question] Is there a way to convert QImage to QVariant?

### ISSUE THREAD

**Issue by matkuki** [jerous86/nimqt#50]
Hi,

I'm trying to call `QMimeData.setImageData` with a `QImage` parameter, but the signature is this:
```nim
proc setImageData*(this: ptr QMimeData, image: QVariant) {.header:headerFile, importcpp:"#.setImageData(@)".} # Public
```
While in the `C++` documentation it says that the conversion from `QImage` to `QVariant` is implicit, that doesn't seem to work in `Nim`:
![image](https://github.com/user-attachments/assets/f4bb01a4-bb34-48c7-bd03-b505aa5c4b7b)

Any ideas on how to achieve this?

**Comment by jerous86** [comment]
Hey matkuki,

according to https://doc.qt.io/qt-6/qimage.html#operator-QVariant, there should be a function in `QImage` that will convert to a `QVariant`, but the corresponding nim function is not present in `qtgui/qimage.nim`.

It seems during the generation of the code, that function was not generated (the codebase is vast, so maybe it was not parsed correctly, or some other issue.) I unfortunately don't have the time now to look for the reason, or to regenerate the new code.

A temporary fixcould be to add it yourself. In your source code you could add something like

``` nim
import nimqt/qimage
import nimqt/qvariant
const headerFile2* = "QtGui/qimage.h"
proc toQVariant*(this: ptr QImage): QVariant {.header:headerFile2, importcpp:"#.operator QVariant()".}
```

which will add a new nim function `QImage.toQVariant`, and can be used like

```nim
let img=newQImage()
echo toQVariant(img)
```

I hope this helps you further
