### ISSUE TITLE
Creating a custom signal and emitting it example?

### ISSUE THREAD

**Issue by matkuki** [jerous86/nimqt#7]
Hi,

Are custom signals supported?
Is there an example  somewhere for creating a custom signal and emitting it?

Regards

**Comment by jerous86** [comment]
I haven't thought about custom signals yet, so currently they're not supported.
That's something for later. I think the main difficulty here is mapping nim types to c++ types.

**Comment by matkuki** [comment]
Ok, no problem. Thanks for the information 👍

**Comment by matkuki** [comment]
Could a signal with just a `string` (`QString`) parameter be possible to implement without much hassle?
Or could some `Nim` message passing system be added to the `Qt` event loop?

**Comment by jerous86** [comment]
I'm going to have a look at it on how to implement it :)

**Comment by matkuki** [comment]
Awesome, thank you 👍👍👍👍

**Comment by jerous86** [comment]
I have commited some simple code implementing custom signals and emitting them :)
Example can be found in `examples/custom_signal.nim` -- I think it will satisfy your nimqt needs :)

**Comment by matkuki** [comment]
Marvelous, works exactly as expected 👍👍👍
Thank you so much 🎉🎉🎉

**Comment by jerous86** [comment]
Glad it is working and useful for you. Don't hesitate too submit more feature requests and/or bug reports! :)
Also curious to see what you're creating with it :)
